previewsEnabled: true
services:
  - type: web
    name: imaginerio-search
    region: oregon
    env: node
    healthCheckPath: /
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - fromGroup: tile-generator
      - key: DATABASE
        value: imagineRio
      - key: IIIF
        value: https://images.imaginerio.org
      - key: DB_URL
        fromDatabase:
          name: imaginerio
          property: connectionString
  - type: cron
    name: imaginerio-database-seeder
    region: oregon
    env: node
    buildCommand: yarn
    startCommand: yarn db:migrate:reset
    schedule: "1 0 * * 6" 
    envVars:
      - fromGroup: tile-generator
      - key: DATABASE
        value: imagineRio
      - key: IIIF
        value: https://images.imaginerio.org
      - key: DB_URL
        fromDatabase:
          name: imaginerio
          property: connectionString
  - type: cron
    name: vector-tile-generator
    region: oregon
    env: docker
    schedule: "1 0 * * 6" 
    repo: https://github.com/imaginerio/vector-tile-generator.git
    envVars:
      - key: AWS_BUCKET
        value: s3://imaginerio-vector/base/{z}/{x}/{y}?timeout=10000
      - fromGroup: tile-generator
databases:
  - name: imaginerio
