previewsEnabled: true
services:
  - type: web
    name: imaginerio-search
    region: oregon
    env: node
    healthCheckPath: /health
    buildCommand: yarn
    startCommand: yarn db:migrate && yarn start
    initialDeployHook: yarn db:job
    envVars:
      - fromGroup: tile-generator
      - fromGroup: scalegrid
      - fromGroup: scalegrid-rio
      - key: DATABASE
        value: imagineRio_GDB
      - key: IIIF
        value: https://images2.imaginerio.org
      - key: COLLECTIONS
        value: '["maps", "plans", "views", "aerials"]'
      - key: OMIT
        value: '["CoastLine"]'
      - key: SMAPSHOT
        value: true
      - key: MAPPING
        value: rio
      - key: CERT_PATH
        value: /etc/secrets/cert.pem
  - type: cron
    name: imaginerio-database-seeder
    region: oregon
    env: node
    buildCommand: yarn
    startCommand: yarn db:job
    schedule: "1 0 * * 6" 
    envVars:
      - fromGroup: tile-generator
      - fromGroup: imaginerio-search
      - fromGroup: scalegrid
      - fromGroup: scalegrid-rio
      - key: DATABASE
        value: imagineRio_GDB
      - key: IIIF
        value: https://images2.imaginerio.org
      - key: COLLECTIONS
        value: '["maps", "plans", "views", "aerials"]'
      - key: OMIT
        value: '["CoastLine"]'
      - key: SMAPSHOT
        value: true
      - key: MAPPING
        value: rio
      - key: CERT_PATH
        value: /etc/secrets/cert.pem
  - type: cron
    name: imaginerio-vector-tile-generator
    region: oregon
    env: docker
    schedule: "1 0 * * 6"
    plan: pro
    repo: https://github.com/imaginerio/vector-tile-generator.git
    envVars:
      - key: AWS_BUCKET
        value: s3://imaginerio-vector/base/{z}/{x}/{y}?timeout=10000
      - fromGroup: tile-generator
      - key: DATABASE
        value: imagineRio_GDB
      - key: MAX_ZOOM
        value: 18
